// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtmE2OEBb6QQjjpt5nYbDS0YgunZadeR4',
    appId: '1:440980593389:web:03b217130d656109e60ae4',
    messagingSenderId: '440980593389',
    projectId: 'metacinema-tung-20260922',
    authDomain: 'metacinema-tung-20260922.firebaseapp.com',
    storageBucket: 'metacinema-tung-20260922.firebasestorage.app',
    measurementId: 'G-B45FJX2H9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJodXmhp7D0RXdeKwXj1TM2L-fTI3vPS0',
    appId: '1:440980593389:android:2713f8e8d3c6ac2ce60ae4',
    messagingSenderId: '440980593389',
    projectId: 'metacinema-tung-20260922',
    storageBucket: 'metacinema-tung-20260922.firebasestorage.app',
  );
}
